spring.application.name=progetto_finale
spring.datasource.url=jdbc:mysql://localhost:3306/progettofinalespring
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# supabase
supabase.url=https://qzsuswmerkqogblfkupl.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6c3Vzd21lcmtxb2dibGZrdXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTExOTYyNjIsImV4cCI6MjEwNjc3MjI2Mn0.6KbbBhfSlhD7qWg80YztcGUSFA0JnDNtLwrfUQXkoHM
supabase.bucket=/storage/v1/object/bucket/
supabase.image=https://qzsuswmerkqogblfkupl.supabase.co/storage/v1/object/public/bucket/


# mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=27cf633704f19a
spring.mail.password=3d64dcdce3c4b5
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true